spring.datasource.url=jdbc:h2:mem:caronadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
# Para o JWT não bloquear tudo de cara enquanto testamos:
spring.security.user.name=user
spring.security.user.password=password
spring.jpa.defer-datasource-initialization=true
server.port=8081